# Generated by Django 3.0.5 on 2020-04-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200430_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='vuews',
            new_name='views',
        ),
    ]
